version: '3.8'
services:
  backend:
    container_name: translator_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ${PATH_TO_MBART50}:/app/models/mbart50
      - ${PATH_TO_NLLB}:/app/models/nllb
      - ${PATH_TO_M2M100}:/app/models/m2m100
      - ${PATH_TO_HELSINKI_NLP}:/app/models/helsinki_nlp
    ports:
      - "${BACKEND_PORT}:8080"  
    environment:
      FLASK_ENV: development 
      MBART50_DIR: /app/models/mbart50
      NLLB_DIR: /app/models/nllb
      M2M100_DIR: /app/models/m2m100
      HELSINKI_NLP_DIR: /app/models/helsinki_nlp
  frontend:
    container_name: translator_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
    ports:
      - "${REACT_APP_FRONTEND_PORT}:3000" 
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    depends_on:
      - backend