version: '3.8'
services:

  backend:
    container_name: translator_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:8080"  
    environment:
      - FLASK_ENV=development 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - BUCKET_NAME=${BUCKET_NAME}

  frontend:
    container_name: translator_frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
    ports:
      - "${REACT_APP_FRONTEND_PORT}:3000" 
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    depends_on:
      - backend

networks:
  default:
    external:
      name: tercuman-network